version: '3.8'

volumes:
  mongodb_data: { driver: local }
  traefik_data: {}

services:
  traefik:
    image: traefik:v2.10
    restart: always
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.https.address=:443"
      - "--certificatesresolvers.le.acme.tlschallenge=true"
      - "--certificatesresolvers.le.acme.email=sugipamo@example.com"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./keys:/letsencrypt
      - traefik_data:/letsencrypt

  rocketchat:
    image: registry.rocket.chat/rocketchat/rocket.chat
    restart: always
    labels:
      traefik.enable: "true"
      traefik.http.routers.rocketchat.rule: "Host(`tasks.local`)"
      traefik.http.routers.rocketchat.tls: "true"
      traefik.http.routers.rocketchat.entrypoints: https
      traefik.http.routers.rocketchat.tls.certresolver: le
    environment:
      MONGO_URL: ${MONGO_URL}
      MONGO_OPLOG_URL: ${MONGO_OPLOG_URL}
      ROOT_URL: ${ROOT_URL}
      PORT: ${PORT}
      DEPLOY_METHOD: ${DEPLOY_METHOD}
    depends_on:
      - mongodb
    ports:
      - "3000:3000" # Traefikがリダイレクトするので、内部でポート3000で起動します

  mongodb:
    image: docker.io/bitnami/mongodb:5.0
    restart: always
    volumes:
      - mongodb_data:/bitnami/mongodb
    environment:
      MONGODB_REPLICA_SET_MODE: ${MONGODB_REPLICA_SET_MODE}
      MONGODB_REPLICA_SET_NAME: ${MONGODB_REPLICA_SET_NAME}
      MONGODB_PORT_NUMBER: ${MONGODB_PORT_NUMBER}
      MONGODB_INITIAL_PRIMARY_HOST: ${MONGODB_INITIAL_PRIMARY_HOST}
      MONGODB_INITIAL_PRIMARY_PORT_NUMBER: ${MONGODB_INITIAL_PRIMARY_PORT_NUMBER}
      MONGODB_ADVERTISED_HOSTNAME: ${MONGODB_ADVERTISED_HOSTNAME}
      MONGODB_ENABLE_JOURNAL: ${MONGODB_ENABLE_JOURNAL}
      ALLOW_EMPTY_PASSWORD: ${ALLOW_EMPTY_PASSWORD}